name: Scala CI

on:
  push:
    branches: [ export ]
  pull_request:
    branches: [ export ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.12
      uses: actions/setup-java@v1
      with:
        java-version: 1.12
    - name: Run tests
      run: sbt test
